server:
  applicationConnectors:
  - type: http
    port: 9000
    bindHost: 127.0.0.1
  adminConnectors:
  - type: http
    port: 9001
    bindHost: 127.0.0.1

logging:
  level: INFO
  loggers:
    blazeDemo: DEBUG

mongoDBConnection:
  credentials:
    username: "admin" 
    password: "secret1234"
  seeds:
    - host: "localhost"
      port: 27017
  database: "blaze-demo"